version: 2
jobs:
  build:
    working_directory: null
    docker:
    - image: debian:stretch
    steps:
    - checkout
    - run:
        name: Greeting
        command: apt install jslint
    - run:
        name: Print the Current Time
        command: date
    - run:
        name: Check for jslint
        command: jslint
