version: 2
jobs:
  build:
    working_directory: null
    docker:
    - image: circleci/node:latest
    steps:
    - checkout
    - run:
        name: yarn install
        command: yarn install
    - run:
        name: Check for jslint
        command: jshint wme_junctionangle.user.js
